### ISSUE TITLE
Bug: Exporting Figma Variables (BETA) using references to other variables throws an error

### ISSUE THREAD

**Issue by Marvellanius** [lukasoppermann/design-tokens#254]
As the title states; When trying to `Save & Export` Figma Variables (BETA), we get the following error:

![image (11)](https://github.com/lukasoppermann/design-tokens/assets/9035837/b783f1e0-02a1-4a56-8022-62a3d914dd3e)

I've been able to narrow it down to it being an issue with variables whose value references another variable.

To narrow it down, I exported all variables in our project with [this plugin](https://www.figma.com/community/plugin/1256972111705530093/Export%2FImport-Variables), which notably _does_ _not_  preserve references, tried to export Figma Variables with the Design Tokens plugin in the new file, which worked fine. Updated one of the variables to contain a reference to another variable as a value, and the above error occured.

Reproduce-file for the issue: https://www.figma.com/file/i9oPPuiKKceCgqMsmHwHsj/Design-Token-variable-export-reproduce

This worked fine at least as late as July 25th, so I suspect #253 might be the cause.

STR:
- Open a Figma file
- Make 2 variables, one with a non-reference value, the other referencing the variable made before
- Try to use Design Tokens to save & export Figma Variables (BETA)

**Comment by maaltone** [comment]
I have similar issues..
`caught TypeError: Cannot read properties of undefined (reading 'value')
    at <anonymous>:640:22114
    at Object.rr (<anonymous>:640:22277)
    at <anonymous>:640:25588
    at Array.map (<anonymous>)
    at fr (<anonymous>:640:25563)
    at onSubmit (<anonymous>:650:874)
    at Object.Te (<anonymous>:2:84110)
    at $e (<anonymous>:2:84264)
    at <anonymous>:2:104124
    at Dr (<anonymous>:2:104218)
(`

**Comment by Marvellanius** [comment]
> I have similar issues.. `caught TypeError: Cannot read properties of undefined (reading 'value') at <anonymous>:640:22114 at Object.rr (<anonymous>:640:22277) at <anonymous>:640:25588 at Array.map (<anonymous>) at fr (<anonymous>:640:25563) at onSubmit (<anonymous>:650:874) at Object.Te (<anonymous>:2:84110) at $e (<anonymous>:2:84264) at <anonymous>:2:104124 at Dr (<anonymous>:2:104218) (`

I have also seen that error; difference between Chrome inspector and Firefox inspector output I'm guessing - the `undefined` referenced in your error _is_ `e.fill`, as `e.fill.value` is referenced in the lines of code that get linked in the error message :)

**Comment by lukasoppermann** [comment]
Hey, thanks I can reproduce it. I will look into it asap.

**Comment by lukasoppermann** [comment]
Fix should be available in version 66. Please reopen if it persists

**Comment by bchipev** [comment]
Unfortunately the latest release causes a faulty "No tokens to export" toast. The issue @Marvellanius and I had (we're colleagues) is still not resolved.

**Comment by lukasoppermann** [comment]
Hey @bchipev can you try again, I hope I fixed it now.

**Comment by Marvellanius** [comment]
@lukasoppermann how would we ensure that the vesion running in Figma is the newest version? As of this morning, I'm still experiencing the same issue as reported (`e.fill is undefined` when trying to export a set of variables with variable-referencing values)

**Comment by lukasoppermann** [comment]
Hey @Marvellanius, by closing and re-opening the figma tab you should normally get the latest version.

**Comment by Marvellanius** [comment]
Then I sadly have to report that the issue persists :( different PC, so pretty sure that should run the latest version then

**Comment by lukasoppermann** [comment]
Hmm, weird, did you try it with a new file? With just one color variable and a another one that references this one?

Or are you per chance using variables from another file?

**Comment by lukasoppermann** [comment]
Hey @Marvellanius it should now work with the tokens references from other files as well.

Yes `fill` comes, because in figma a color token is a color and a color is an object with a fill property.

**Comment by Marvellanius** [comment]
Yes! I just now had a working export while trying to reproduce my issue, so can confirm it now works! Thanks so much for the quick turnaround :smile:

**Comment by UgoJau** [comment]
Hello there happy to ear it its working for some, I get : 
`Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at <anonymous>:640:22206
    at Object.ar (<anonymous>:640:22369)
    at <anonymous>:640:25680
    at Array.map (<anonymous>)
    at pr (<anonymous>:640:25655)
    at onSubmit (<anonymous>:650:873)
    at Object.Te (<anonymous>:2:84110)
    at $e (<anonymous>:2:84264)
    at <anonymous>:2:104124
    at Dr (<anonymous>:2:104218)
(anonymous) @ VM2271:640
ar @ VM2271:640
(anonymous) @ VM2271:640
pr @ VM2271:640
onSubmit @ VM2271:650
Te @ VM2271:2
$e @ VM2271:2
(anonymous) @ VM2271:2
Dr @ VM2271:2
Ir @ VM2271:2
(anonymous) @ VM2271:2
uu @ VM2271:2
Ae @ VM2271:2
Br @ VM2271:2
Kn @ VM2271:2
qn @ VM2271:2`

It works if I try with variables with no aliases, but as soon as I have some it doesn't.

In this file we have primitives -> Raw
Semantic -> aliases primitives
Tokens -> aliases semantic

Any help would be awesome. @lukasoppermann 
Thanks
